channels:
- conda-forge
- pytorch
dependencies:
- python=3.11.12
- pip<=25.0

- pip:
  - mlflow==3.2.0
  - torch==2.6.0
  - torchvision==0.21.0
  - torch-geometric==2.6.1
  - torch_geometric_temporal==0.56.1
  - torch_sparse==0.6.18
  - torch_scatter==2.1.2
  - numpy==1.26.4

name: mlflow-env

